StufShop/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.Models;
using StufShop.Models;

namespace StufShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : BaseController
    {
        private UserManager<User> UserManager;
        private SignInManager<User> SignInManager;
        public HomeController(UserManager<User> UserManager, SignInManager<User> SignInManager) : base(UserManager)
        {
            this.UserManager = UserManager;
            this.SignInManager = SignInManager;
        }
        // GET: HomeController

        public async Task<IActionResult> Index()
        {
            var user = await UserManager.FindByNameAsync(User.Identity.Name);
            var claim = await UserManager.GetClaimsAsync(user);
            if (claim.Any(t => t.Value != "Operator"))
            {
              await  SignInManager.SignOutAsync();
              return RedirectToAction("Signin","Account");
            }
            return View();
        }


    }
}

StufShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.Models;
using StufShop.Models.Carts;
using StufShop.Models.Stuf;

namespace StufShop.Controllers
{
    public class CartController : Controller
{
        private UserManager<User> _UserManager;
        private ICartRopository _CartRopo;
        private IStufRepository _StufRepo;
        public CartController(UserManager<User> UserManager, ICartRopository CartRopo, IStufRepository StufRepo)
        {
            _UserManager = UserManager;
            _CartRopo = CartRopo;
            _StufRepo = StufRepo;
        }
    public async Task<IActionResult> Index(int? stufid, int? count = 1 )
    {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Signin", "Account");
            }
            else 
            {
                var user = await _UserManager.FindByNameAsync(User.Identity.Name);
                var cart = await _CartRopo.Find(user.Id);
                if (stufid != null)
                {
                    var Stuf = await _StufRepo.FindAsync((int)stufid);
                    if (cart != null && Stuf.Count >= count)
                    {
                        if (cart.cartItems.Any(c=>c.Stuf.Id == stufid ))
                        {
                            var cartItem = cart.cartItems.FirstOrDefault(c => c.Stuf.Id == stufid);
                            await _CartRopo.Update(new CartItems
                            {
                                Id=cartItem.Id,
                                number= (int)count ,
                                Price = Stuf.Price,
                            });
                            await _CartRopo.save();
                            return RedirectToAction("Index", "Order");
                        }
                        else
                        {
                            await _CartRopo.Add(new CartItems
                            {
                                Cart = cart,
                                Stuf = Stuf,
                                number = (int)count,
                                Price = Stuf.Price
                            });

                            await _CartRopo.save();

                            return RedirectToAction("Index" , "Order");
                        }

                    }
                    else
                    {
                        var newcart = new Cart
                        {
                            Customer = user,
                            Date = DateTime.Now,
                            PayState = PayState.UnPaied,
                            OrderDate = DateTime.Now
                        };
                        await _CartRopo.Add(newcart);
                        await _CartRopo.save();

                        var cartfinal = await _CartRopo.Find(newcart.Id);
                        await _CartRopo.Add(new CartItems
                        {
                            Cart = cartfinal,
                            Stuf = Stuf,
                            number = (int)count,
                            Price = Stuf.Price
                        });

                        await _CartRopo.save();

                        return RedirectToAction("Index", "Order");
                    }
                    
                }
                else 
                {
      
                    return RedirectToAction("List","Home");
                }
            }
        
    }
    public async Task<IActionResult> Remove(int id)
    {
           await _CartRopo.Delete(id);
            await _CartRopo.save();
            return new RedirectResult("/Cart");
    }
}
}

StufShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using StufShop.Models;
using StufShop.Models.Stuf;
using Microsoft.EntityFrameworkCore;

namespace StufShop.Controllers
{
    public class HomeController : Controller
    {
        private UserManager<User> UserManager;
        private SignInManager<User> SignInManager;
        private IStufRepository _StufRepository;
        private ApplicationDbContext _context;
        public HomeController(UserManager<User> UserManager, SignInManager<User> SignInManager , IStufRepository StufRepository,
            ApplicationDbContext context)
        {
            this.UserManager = UserManager;
            this.SignInManager = SignInManager;
            _StufRepository = StufRepository;
            _context = context;
        }
        public async  Task<IActionResult> Index()
        {
            if (User.Identity.Name != null )
            {
                var user = await UserManager.FindByNameAsync(User.Identity.Name);
                var claim = await UserManager.GetClaimsAsync(user);
                if (user.UserName == "admin")
                {
                    await SignInManager.SignOutAsync();
                    return Redirect("/");
                }
            }

            return View();
        }
        public async Task<IActionResult> List( )
        {
            var stuf = await _context.Stufs.ToListAsync();

            return View("index-2", stuf);

        }

        public async Task<IActionResult> ViewAllStuf()
        {
            var stufs =await _context.Stufs.ToListAsync();
            
            return View(stufs);
        }
        public async Task<IActionResult> Details(int id)
        {
            var stuf =await _StufRepository.FindAsync(id);
            
            return View(stuf);
        }

    }
}

StufShop/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StufShop.Models;
using StufShop.Models.Profile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace StufShop.Controllers
{
    public class ProfileController : Controller
    {

        private IAddressRepository _AddressRepository;
        private IUserValidator<User> _UserValidator;
        private SignInManager<User> _signInManager;
        private UserManager<User> _UserManager;
        private IPasswordHasher<User> _passwordHasher;
        private IPasswordValidator<User> _passwordValidator;
        public ProfileController(IAddressRepository AddressRepository, UserManager<User> UserManager, IUserValidator<User> UserValidator,
            IPasswordValidator<User> passwordValidator, IPasswordHasher<User> passwordHasher, SignInManager<User> signInManager)
        {
            _UserManager = UserManager;
            _AddressRepository = AddressRepository;
            _signInManager = signInManager;
            _passwordHasher = passwordHasher;
            _passwordValidator = passwordValidator;
            _UserValidator = UserValidator;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(string province, string city, string address, string tel)
        {
            var customer = await _UserManager.FindByNameAsync(User.Identity.Name);
            await _AddressRepository.Add(new Address
            {
                city = city,
                Country = province,
                Location = address,
                Phone = tel,
                Customer = customer
            });
            await _AddressRepository.Save();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Details()
        {
            var user = await _UserManager.FindByNameAsync(User.Identity.Name);

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Details(string Fname, string Lname, string Username, string Password, string ConformPassword)
        {
            var user = await _UserManager.FindByNameAsync(User.Identity.Name);
            if (Password != ConformPassword && !string.IsNullOrEmpty(Password))
            {
                ViewBag.Message = "رمز عبور با تاییده رمز عبور برابر نیست !";
                return View(user);
            }
  
            user.FirstName = Fname;
            user.LastName = Lname;

            var validEmail = await _UserValidator.ValidateAsync(_UserManager, user);
            var passiden = await _passwordValidator.ValidateAsync(_UserManager, user, Password);
            if (passiden.Succeeded)
            {
                user.PasswordHash = _passwordHasher.HashPassword(user, Password); 
            }
            else
            {
                AddErrorsFromResult(passiden);
            }

            await _signInManager.PasswordSignInAsync(user, Password, true, false);
            var result = await _UserManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                AddErrorsFromResult(result);
            }
            return View();
        }
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

StufShop/Views/Home/Details.cshtml
@model StufShop.Models.Stuf.Stuf
@{
    var bigpic = "";
}
@section Style
{
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/css/camera.css" rel="stylesheet" />
    <link href="~/css/form.css" rel="stylesheet" />
    <link href="~/css/ie.css" rel="stylesheet" />
    <link href="~/css/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/css/skeleton.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/Admin/style.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
}

<div>
    <div class="container_12">
        <div class="grid_12">
            <h2>جزئیات محصولات</h2>

            @if (Model != null)
            {
                <form asp-action="Index" asp-controller="Cart" asp-route-stufid="@Model.Id" method="post">
                <div class="card mb-3 dir" >
                    <img class="card-img" src="~/images/itemPics/page3_big_pic-@Model.Id .jpg" style="height: 300px;width: 400px;margin: 0 auto;" />
                    <div class="card-body">
                        <h5 class="card-title">@Model.Title</h5>
                        <p class="card-text">@Model.Description</p>
                        <button type="submit"  class="btn btn-primary margin-b">اضافه به سبد</button>
                        <div class="card-footer text-muted ">
                            @Model.Price قیمت
                            <h4  style="display: inline;float: left;top: -25px;position: relative;">تعداد سفارش  </h4>
                            <input type="number" min="1" max="@Model.Count" style=" width: 100px;margin: 0 10px 0;float: left;"  name="count" value="1" />
                            </div>
                    </div>
                </div>

                </form>
            }
            else
            {
                <h2> محصولی با این مشخصات موجود نیست.</h2>
            }



        </div>
    </div>
</div>

StufShop/Views/Home/Index.cshtml
<div class="hline2">
    <div class="container_12">
        <div class="grid_12">

            <div class="slider_wrapper">
                <div class="" id="camera_wrap">
                    <div data-src="images/slide1.jpg">
                        <div class="caption fadeIn">
                            <div class="caption_bg">
                                <span class="slider_txt1">بهترین محصولات بهداشتی  </span>
                                <div class="slogans_bottom">
                                    <span class="slider_txt2">انواع لوازم و ابزار نظافت و شستشو و ابزار و وسایل گردگیری</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div data-src="images/slide2.jpg" style="height: 80% !important;">
                        <div class="caption fadeIn">
                            <div class="caption_bg">
                                <div class="slogans_bottom">
                                    <span class="slider_txt2"> ارائه ی لوازم خانگی آلمانی</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



<div class="hline2 v2">
    <div class="container_12">
        <div class="grid_12">
            <h2>محصولات</h2>

            <div class="list_carousel responsive">
                <ul id="carousel">
                    <li>
                        <figure><a href="images/page1_big_pic1.jpg" class="magnifier2"><img src="images/page1_pic1.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">اجاق گاز اخوان</span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>
                    <li>
                        <figure><a href="images/page1_big_pic2.jpg" class="magnifier2"><img src="images/page1_pic2.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">یخچال امرسان</span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>
                    <li>
                        <figure><a href="images/page1_big_pic3.jpg" class="magnifier2"><img src="images/page1_pic3.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">مایع تمیز کننده clean</span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>
                    <li>
                        <figure><a href="images/page1_big_pic4.jpg" class="magnifier2"><img src="images/page1_pic4.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">یخچال فریزر ساید بای ساید </span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>

                    <li>
                        <figure><a href="images/page1_big_pic1.jpg" class="magnifier2"><img src="images/page1_pic1.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">اجاق گاز اخوان</span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>
                    <li>
                        <figure><a href="images/page1_big_pic2.jpg" class="magnifier2"><img src="images/page1_pic2.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">یخچال امرسان</span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>
                    <li>
                        <figure><a href="images/page1_big_pic3.jpg" class="magnifier2"><img src="images/page1_pic3.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">مایع تمیز کننده clean</span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>
                    <li>
                        <figure><a href="images/page1_big_pic4.jpg" class="magnifier2"><img src="images/page1_pic4.jpg" alt=""><span class="zoom"></span></a></figure>
                        <p><span class="txt2">یخچال فریزر ساید بای ساید </span><br>توضیحات اینجا قرار میگیرد<br></p>
                    </li>


                </ul>
                <div class="clear"></div>
                <div class="carousel_btns">
                    <a class="prev" id="prev" href="javascript:;"></a>
                    <a class="next" id="next" href="javascript:;"></a>
                </div>
            </div>



        </div>
    </div>
</div>

 

StufShop/Views/Home/ViewAllStuf.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<StufShop.Models.Stuf.Stuf>

@section Style
 {
    <title>Restaurant</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/css/reset.css" type="text/css">
    <link rel="stylesheet" href="~/css/layout.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
    <link href="~/css/fonts.css" rel="stylesheet" />
    <link href="~/css/Admin/style.css" rel="stylesheet" />
}

@section Scripts
{
    <script type="text/javascript" src="js/jquery-1.6.js"></script>
    <script type="text/javascript" src="js/cufon-yui.js"></script>
    <script type="text/javascript" src="js/cufon-replace.js"></script>
    <script type="text/javascript" src="js/Forum_400.font.js"></script>
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="js/tms-0.3.js"></script>
    <script type="text/javascript" src="js/tms_presets.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/atooltip.jquery.js"></script>
    <script type="text/javascript">Cufon.now();</script>


}
@inject UserManager<User> userManager
@inject SignInManager<User> signInManager
@{
    string displayname = "";
    User Customer = null;
    if (User.Identity.IsAuthenticated)
    {
        Customer = await userManager.FindByNameAsync(User.Identity.Name);
        displayname = Customer.FirstName + " " + Customer.LastName;
    }
}
<div id="page1">
    <div class="body6">
        <div class="body1">
            <div class="body5">
                <div class="main">
                    <!-- header -->
                    <header>
                        <h1><a href="index.html" id="logo">سایت رستوران تست</a></h1>
                        <nav>
                            <ul id="top_nav">
                                @if (Customer == null & displayname == "")
                                {
                                    <li><a asp-action="Index" asp-controller="Home"><img src="images/icon_1.gif" alt=""></a></li>
                                    <li><a asp-action="about-us" asp-controller="Home"><img src="images/icon_3.gif" alt=""></a></li>
                                }
                                else
                                {
                                    <li><a class="text-info" asp-action="Index" asp-controller="Profile"> کاربر @displayname به سایت خوش امدید
                                    <li class="fa fa-account" /></a></li>

                                }
                            </ul>
                        </nav>
                        <nav>
                            <ul id="menu">
                                <li class="active"><a asp-action="Index">رستوران</a></li>
                                <li><a asp-action="ViewAllFood" asp-controller="Home">غذاها </a></li>
                                <li><a asp-action="Index" asp-controller="Order">سبد خرید</a></li>
                                @if (Customer == null & displayname == "")
                                {
                                    <li><a asp-action="Signin" asp-controller="Account">ورود به سایت </a></li>
                                    <li><a asp-action="Signup" asp-controller="Account">ثبت نام </a></li>
                                }
                                else
                                {
                                    <li><a asp-action="Details" asp-controller="Profile">  حساب کاربری</a></li>
                                    <li><a asp-action="Details" asp-controller="Profile">  آدرس</a></li>
                                    <li><a asp-action="Signout" asp-controller="Account"> خروج</a></li>
                                }
                            </ul>
                        </nav>
                    </header>
                    <!-- / header -->
                    <!-- content -->
                    <article id="content">
                        <div class="products">
                            @if (Model != null)
                            {
                                foreach (var food in Model)
                                {
                                    <div class="card-column">

                                        <div class="card" style="width: 18rem;">
                                            <img src="/images/Gallery/@food.Id .jpg" class="card-img-top wrapp" alt="">
                                            <div class="card-body">
                                                <h5 class="card-title">@food.Title</h5>
                                                <p class="card-text">@food.Description</p>
                                                <a asp-action="Index" asp-controller="Cart" asp-route-Foodid="@food.Id" class="btn btn-primary">اضافه به سبد</a>
                                            </div>
                                        </div>

                                    </div>
                                }




                            }
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>

    <div class="body3">
        <div class="body4">
            <div class="main">
                <!-- footer -->
                <footer>
                    <div class="wrapper footer-border">
                        <section class="col1 pad_left1">
                            <h3>ارتباط با ما:   <span>09222222</span></h3>

                        </section>
                        <section class="col2 pad_left1">
                            <h3>در شبکه های اجتماعی ما را دنبال کنید:</h3>
                            <ul id="icons">
                                <li><a href="#" class="normaltip" title="Facebook"><img src="images/icon1.gif" alt=""></a></li>
                                <li><a href="#" class="normaltip" title="Linkedin"><img src="images/icon2.gif" alt=""></a></li>
                                <li><a href="#" class="normaltip" title="Twitter"><img src="images/icon3.gif" alt=""></a></li>
                                <li><a href="#" class="normaltip" title="Delicious"><img src="images/icon4.gif" alt=""></a></li>
                                <li><a href="#" class="normaltip" title="Technorati"><img src="images/icon5.gif" alt=""></a></li>
                            </ul>
                        </section>
                    </div>
                    <!-- {%FOOTER_LINK} -->
                </footer>
                <!-- / footer -->
            </div>
        </div>
    </div>
</div>

StufShop/Views/Home/index-2.cshtml
@model IEnumerable<StufShop.Models.Stuf.Stuf>
@{
    var bigpic = "";
}
@section Style
{
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/css/camera.css" rel="stylesheet" />
    <link href="~/css/form.css" rel="stylesheet" />
    <link href="~/css/ie.css" rel="stylesheet" />
    <link href="~/css/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/css/skeleton.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/Admin/style.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
}

<div>
    <div class="container_12">
        <div class="grid_12">
            <h2>محصولات</h2>

            <div class="products">
                @if (Model != null)
                {
                    @foreach (var stuf in Model)
                    {
                        <div class="card-column">

                            <div class="card" style="width: 18rem;">
                                <figure class="figure_gall"><a href="/images/itemPics/page3_big_pic-@stuf.Id .jpg" class="magnifier2"><img src="/images/itemPics/page3_pic-@stuf.Id .jpg" class="card-img-top wrapp " alt=""><span class="zoom"></span></a></figure>
                                <div class="card-body dir">
                                    <a asp-action="Details" asp-controller="Home" asp-route-id="@stuf.Id"><h5 class="card-title">@stuf.Title</h5></a>
                                    <p class="card-text">@stuf.Description</p>
                                    <a asp-action="Index" asp-controller="Cart" asp-route-stufid="@stuf.Id" class="btn btn-primary margin-b">اضافه به سبد</a>
                                    <div class="card-footer text-muted ">
                                        @stuf.Price قیمت
                                    </div>
                                </div>
                            </div>

                        </div>
                    }
                }

            </div>



        </div>
    </div>
</div>