StufShop/Models/Stuf/GoupBrandView.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.Models.Stuf;
using StufShop.Migrations;

namespace StufShop.Models.Stuf
{
    public class GoupBrandView
    {
        public SelectList Brands { get; set; }
        public SelectList Groups { get; set; }
        public Stuf StufShop { get; set; }
    }
}

StufShop/Models/Stuf/IStufItemRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StufShop.Models.Stuf
{
    public interface IStufItemRepository
    {
        Task Add(StufItem StufItem);
        Task Update(StufItem StufItem);
        Task Update(List<StufItem> StufItem);
        Task Delete(int? id);
        Task<List<StufItem>> search(int StufItem);
        Task<StufItem> Find(int id);
        Task Save();
    }
}

StufShop/Models/Stuf/IStufRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.Models.Stuf;

namespace StufShop.Models.Stuf
{
   public  interface IStufRepository
    {
        Task AddAsync(Stuf StufShop);
        void Update(Stuf StufShop);
        Task DeleteAsync(int Id);
        Task<Stuf> FindAsync(int id);
        Task<Stuf> StufDetailAsync(int Stufid);
        Task<IEnumerable<Stuf>> SearchAsync(int? id , string PrimaryTitle);
        Task<IEnumerable<Stuf>> SearchAsync(int Groupid);
        Task SaveAsync();
    }
}

StufShop/Models/Stuf/State.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StufShop.Models.Stuf
{
    public enum State:byte
    {
        Enabled=1,
        Disable=2
    }
}

StufShop/Models/Stuf/Stuf.cs
using System;
using System.Collections.Generic;
using StufShop.Models.Groups;
using StufShop.Models;
using StufShop.Models.Stuf;

namespace StufShop.Models.Stuf
{
    public class Stuf
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Group group { get; set; }
        public int groupid { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public State state { get; set; }

        public User Creator { get; set; }
        public DateTime CreateDate { get; set; }

        public List<StufItem> StufItems { get; set; }
    }
}

StufShop/Models/Stuf/StufItem.cs
 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.Models;

namespace StufShop.Models.Stuf
{
    public class StufItem
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public double? Discount { get; set; }
        public byte Quantity { get; set; }

        public Stuf Stuf { get; set; }

        public State state { get; set; }
        public User Creator { get; set; }
        public DateTime CreateDate { get; set; }

    }
}

StufShop/Models/ViewModels/Product/StufView.cs
using StufShop.Models.Stuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.Models.Groups;

namespace StufShop.Models.ViewModels.Product
{
    public class StufShopView
    {
        public int Id { get; set; }
        public string PrimaryTitle { get; set; }
        public string SecondaryTitle { get; set; }
        public string Description { get; set; }
        public Group group { get; set; }
        public int Count { get; set; }
 
        public State state { get; set; }

        public string Creator { get; set; }
        public string CreateDate { get; set; }

    }
}

StufShop/Areas/Admin/Controllers/StufController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StufShop.InfraStructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Globalization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_Digikala.Areas.Admin;
using StufShop.Models;
using StufShop.Models.Stuf;
using StufShop.Models.Groups;
using StufShop.Models.ViewModels.Product;
using StufShop.Models.Carts;
using StufShop.Models.Profile;
using StufShop.Models;


namespace StufShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StufController : BaseController
    {

        private UserManager<User> UserManager;
        private IStufRepository _StufRepo;
        private IGroupRepository groupRepo;
        private IHostingEnvironment hosting;
        private IStufItemRepository StufItemRepo;
        private ApplicationDbContext _context;

        public StufController(UserManager<User> userManager, IStufRepository StufRepo,
            IGroupRepository groupRepo, IHostingEnvironment hosting, IStufItemRepository StufItemRepo, ApplicationDbContext context) : base(userManager)
        {
            UserManager = userManager;
            _StufRepo = StufRepo;
            this.groupRepo = groupRepo;
            this.hosting = hosting;
            _context = context;
            StufItemRepo = StufItemRepo;
        }


        #region HttpGet 
        public IActionResult Index(int Id)
        {
            return View();
        }


        public async Task<IActionResult> list(int? id, string PrimaryTitle)
        {
            var breadcrumbs = new List<breadcrumb>()
            {
                new breadcrumb
                {
                    Title="صفحه اصلی ",
                    Url ="/"
                } ,
                new breadcrumb
                {
                    Title="لیست کالا ها ",
                    Url =""
                }
            };

            var products = await _StufRepo.SearchAsync(id, PrimaryTitle);
            var StufList = new List<StufShopView>();
            var persian = new PersianCalendar();
            if (products != null)
            {
                foreach (var item in products)
                {
                    StufList.Add(new StufShopView
                    {
                        Id = item.Id,
                        PrimaryTitle = item.Title,
                        Description = item.Description,
                        group = new Group
                        {
                            Id = item.group.Id,
                            GroupTitle = item.group.GroupTitle
                        },
                        state = item.state,
                        Creator = item.Creator?.FirstName + " " + item.Creator?.LastName,
                        CreateDate = persian.PersianDate(item.CreateDate),
                        Count = item.Count
                    });
                }

            }
            return View(StufList);
        }


        public async Task<IActionResult> Add()
        {

            return View();
        }


        public async Task<IActionResult> Edit(int Id)
        {
            ViewBag.Idd = 1;

            var GroupbrandModel = new Models.Stuf.GoupBrandView();

            var stuf = await _StufRepo.FindAsync(Id);
            GroupbrandModel.StufShop = new Stuf
            {
                Id = Id,
                groupid = stuf.groupid,
                Title = stuf.Title,
                state = stuf.state,
                Description = stuf.Description,
                Price = stuf.Price,
                Count = stuf.Count
            };
            var selectgroup = await groupRepo.FindGroupsAsync();

            GroupbrandModel.Groups = new SelectList(selectgroup, "Id", "Title");

            return View("Add", GroupbrandModel);
        }


        public async Task<IActionResult> Delete(int Id)
        {
            var stufCarts = await _context.cartItems.Include(d => d.Stuf)
                    .Where(s => s.Stuf.Id == Id).ToListAsync();
            _context.cartItems.RemoveRange(stufCarts);

            var Pitem = await _StufRepo.FindAsync(Id);
            if (Pitem != null)
            {
                await _StufRepo.DeleteAsync(Pitem.Id);
                await _StufRepo.SaveAsync();
            }

            return RedirectToAction("List");
        }

        #endregion /HttpGet

        #region HttpPost
        [HttpPost]
        public async Task<IActionResult> save(int? Id, string PrimaryTitle, string Description,
             int Group, int Price, int count, byte state, IFormFile Photo)
        {
            if (Id == null)
            {
                if (Photo.Length < 1000000)
                {


                    var user = _context.User.FirstOrDefault(s => s.UserName == User.Identity.Name);
                    Stuf Stuf = new Stuf()
                    {
                        groupid = Group,
                        Title = PrimaryTitle,
                        state = (State)state,
                        Description = Description,
                        Creator = user,
                        CreateDate = DateTime.Now,
                        Price = Price,
                        Count = count
                    };

                    await _StufRepo.AddAsync(Stuf);
                    await _StufRepo.SaveAsync();
                    var productid = Stuf.Id;

                    var ext = Path.GetExtension(Photo.FileName);
                    var path = Path.Combine(hosting.WebRootPath + "\\images\\itemPics\\page3_pic-" + productid + " " + ext);
                    using (var filestream = new FileStream(path, FileMode.Create))
                    {
                        await Photo.CopyToAsync(filestream);
                    }
                    return RedirectToAction("List");
                }
                else
                {
                    ModelState.AddModelError("Photo", "حداکثر سایز عکس باید  1 مگا بایت باشد !");
                    return View("Add");
                }
            }
            else
            {//edit
                var op = await UserManager.FindByIdAsync(this.Operator.Id);
                Stuf product = new Stuf
                {
                    Id = (int)Id,
                    groupid = Group,
                    Title = PrimaryTitle,
                    state = (State)state,
                    Description = Description,
                    Price = Price,
                    Count = count
                };
                _StufRepo.Update(product);
                await _StufRepo.SaveAsync();

                return RedirectToAction("List");
            }
        }



        #endregion /HttpPost
    }
}

StufShop/Controllers/StufController.cs
using Microsoft.AspNetCore.Mvc;
using StufShop.Models.Stuf;
using StufShop.Models.ViewModels.Product;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StufShop.InfraStructure;

namespace StufShop.Controllers
{
    public class StufController : Controller
    {
        private IStufRepository _StufRepository;
        public StufController(IStufRepository StufRepository)
        {
            _StufRepository = StufRepository;
        }
        public async Task<IActionResult> Index(int id)
        {
            var Food = await _StufRepository.StufDetailAsync(id);
            return View(Food);
        }
 
        public async Task<IActionResult> FoodListByGroup(int Groupid)
        {
            var Foodview = new List<StufListView>();

            var Plist = await _StufRepository.SearchAsync(Groupid);
            foreach (var item in Plist)
            {
                Foodview.Add(new StufListView
                {
                    Id = item.Id,
                    PrimaryTitle = item.Title,
                    ImageUrl = $"{item.Id}.jpg",
                    Price = item.StufItems.Select(p => p.Price).FirstOrDefault().ToString("N0"),
                    Group = item.group
                });
            }
            return View("List", Foodview);
        }
        public IActionResult SendComment(string comment, int FoodId)
        {
            
            return new RedirectResult("/Food/Index/" + FoodId);
        }
    }
}

StufShop/Areas/Admin/Views/Stuf/Add.cshtml
@using Microsoft.EntityFrameworkCore
@using StufShop.Models.Groups
@using StufShop.Models.ViewModels.Product
@using StufShop.Models
@model StufShop.Models.Stuf.GoupBrandView

@inject ApplicationDbContext _context;
@{
    var idd = ViewBag.Idd;
    ViewData["Title"] = (idd != null ? "تغییر  کالا" : "افزودن کالا");

    var groups = await _context.Groups.ToListAsync();
}
<h3>@(idd != null ? "تغییر  کالا" : "افزودن کالا")</h3>

@section breadcrumb{
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb bg-dark bg-opacity-10">
            <li class="breadcrumb-item align-text-top "><a class="pe-1  m-1  breadcrumb-link" asp-area="Admin" asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
            <li class="breadcrumb-item " aria-current="page" style=" margin-right: 20px;"> @(idd != null ? "تغییر  کالا" : "افزودن کالا") </li>
        </ol>
    </nav>

    <div class="card ">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h1 class="h5">@(idd != null ? "تغییر  کالا" : "افزودن کالا")</h1>
            <div>
                <a class="btn btn-success btn-sm" asp-area="Admin" asp-action="List">لیست کالا</a>
            </div>
        </div>
        <div class="card-body ">

            <form action="@Url.Action("save")" class="form-control validnd" method="post" enctype="multipart/form-data" novalidate>
                @{
                    if (idd != null)
                    {
                        <input type="hidden" value="@Model.StufShop.Id" name="id" />
                    }
                }
                <div class="row  mb-3 mt-3">
                    <label for="PrimaryTitletxt" class="form-label col-md-1">نام اصلی:</label>
                    <div class="col-md-6">
                        @if (Model?.StufShop != null)
                        {
                            <input class="form-control " id="PrimaryTitletxt" autocomplete="off" maxlength="50" name="PrimaryTitle" value="@Model.StufShop.Title" required>

                        }
                        else
                        {
                            <input class="form-control " id="PrimaryTitletxt" autocomplete="off" maxlength="50" name="PrimaryTitle" required>

                        }
                        <div class="invalid-feedback">لطفا نام اصلی را وارد کیند</div>
                    </div>
                </div>
 

                <div class="row  mb-3 mt-3">
                    <label for="Descriptiontxt" class="form-label col-md-1">توضیحات:</label>
                    <div class="col-md-6">
                        @if (Model?.StufShop != null)
                        {
                            <textarea class="form-control " rows="4" maxlength="200" autocomplete="off" id="Descriptiontxt" name="Description" required>@Model.StufShop.Description</textarea>

                        }
                        else
                        {
                            <textarea class="form-control " rows="4" maxlength="200" autocomplete="off" id="Descriptiontxt" name="Description" required></textarea>

                        }
                        <div class="invalid-feedback">لطفا توضیحات را وارد کیند</div>
                    </div>
                </div>



                <div class="row mb-3">
                    <label for="ddlgroup" class="form-label col-md-1">گروه:</label>
                    <div class="col-md-6">
                        <select class="form-select" id="ddlgroup"   name="Group" required>
                            <option selected disabled value="">لطفا انتخاب کنید...</option>
                            @foreach (var group in groups)
                            {
                                <option  value="@group.Id">@group.GroupTitle</option>
                            }
                        </select>
                        <div class="invalid-feedback">لطفا گروه را انتخاب کنید</div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="ddlPrice" class="form-label col-md-1">قیمت:</label>
                    <div class="col-md-6">
                        @if (Model == null)
                        {
                            <input class="form-control" type="text" id="ddlPrice" name="Price" required/>

                        }
                        else
                        {
                            <input class="form-control" type="text" id="ddlPrice" value="@Model.StufShop.Price" name="Price" required/>

                        }
                        <div class="invalid-feedback">لطفا قیمت را انتخاب کنید</div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="ddlCount" class="form-label col-md-1">تعداد:</label>
                    <div class="col-md-6">
                        @if (Model == null)
                        {
                            <input class="form-control" type="number" id="ddlCount" name="count" required/>

                        }
                        else
                        {
                            <input class="form-control" type="text" id="ddlCount" value="@Model.StufShop.Count" name="count" required/>

                        }
                        <div class="invalid-feedback">لطفا قیمت را انتخاب کنید</div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="ddlState" class="form-label col-md-1">وضعیت:</label>
                    <div class="col-md-6">
                        <select class="form-select" id="ddlState" name="state" required>
                            @if (Model != null && Model?.StufShop?.state == StufShop.Models.Stuf.State.Enabled)
                            {
                                <option disabled value="">لطفا انتخاب کنید...</option>
                                <option selected="selected" value="1">فعال</option>
                                <option value="2">غیر فعال</option>


                            }
                            else if (Model != null && Model?.StufShop?.state == StufShop.Models.Stuf.State.Disable)
                            {
                                <option disabled value="">لطفا انتخاب کنید...</option>
                                <option value="1">فعال</option>
                                <option selected="selected" value="2">غیر فعال</option>

                            }
                            else if (Model?.StufShop == null)
                            {
                                <option selected disabled value="">لطفا انتخاب کنید...</option>
                                <option value="1">فعال</option>
                                <option value="2">غیر فعال</option>
                            }
                        </select>
                        <div class="invalid-feedback">لطفا وضعیت را انتخاب کنید</div>
                    </div>
                </div>

                <div class="row  mb-3 mt-3">
                    <label for="formPhoto" class="form-label col-md-1">تصویر:</label>
                    <div class="col-md-6">
                        @if (Model != null)
                        {
                            <input type="file" class="form-control-File" id="formPhoto" maxlength="50" name="Photo" autocomplete="off">

                        }
                        else
                        {
                            <input type="file" class="form-control-File" id="formPhoto" maxlength="50" name="Photo" autocomplete="off" required>

                        }
                        <div class="invalid-feedback">لطفا   Photo را وارد کیند</div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-success pe-3 ps-3 mb-3">ثبت </button>

                    </div>
                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
            </form>





        </div>
    </div>

}
@section Scripts{
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.querySelectorAll('.validnd')

            // Loop over them and prevent submission
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
        })()
    </script>
}

StufShop/Areas/Admin/Views/Stuf/Edit.cshtml
@{
    ViewData["Title"] = "تغییر کالا ها";
}
<h2>تغییر کالا ها</h2>

StufShop/Areas/Admin/Views/Stuf/Index.cshtml
@{
    ViewData["Title"] = "جزئیات کالا";
}
<h2>جزئیات کالا</h2>

StufShop/Areas/Admin/Views/Stuf/List.cshtml
@using Microsoft.EntityFrameworkCore
@using StufShop.Models
@model List<StufShop.Models.ViewModels.Product.StufShopView>

@inject ApplicationDbContext _context;
@{
    var productid =
     ViewData["Title"] = "لیست کالا ها";
    int couter = 1;

    var groups = await _context.Groups.ToListAsync();
}

@section breadcrumb{
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb bg-dark bg-opacity-10">
            <li class="breadcrumb-item align-text-top "><a class="pe-1   m-1 breadcrumb-link" asp-area="Admin" asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>

        </ol>
    </nav>


    <div class="card ">

        <div class="card-header ">
            <div class="d-flex align-items-center justify-content-between">
                <h1 class="h5">لیست کالا ها</h1>
                <div>
                    <a class="btn btn-primary btn-sm " data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">فیلتر</a>
                    <a class="btn btn-success btn-sm " asp-area="Admin" asp-controller="Stuf" asp-action="Add">افرزودن کالا</a>
                </div>
            </div>
        </div>
        <div class="card-body ">

            <div class="row justify-content-center">

                <div class="collapse col-md-6 " id="collapseExample">
                    <div class="card  mb-3  justify">
                        <div class="card-header style-1  overflow-hidden m-0 w-100 bg-info text-light">فیلتر</div>
                        <div class="card-body">

                            <form action="" class="form-control" method="post">

                                <div class="row  mb-3">
                                    <label for="Idtxt" class="form-label col-md-2">شناسه:</label>
                                    <div class="col-md-10">
                                        <input class="form-control " id="Idtxt" name="id">
                                    </div>
                                </div>
 
                                <div class="row">
                                    <div class="col-md-5"></div>
                                    <div class="col-md-4">
                                        <button type="submit" class="btn btn-primary pe-2  mb-2 text-center">فیلتر</button>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
 

            <table class="table table-striped table-success">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col" style="width:25%">نام</th>
                        <th scope="col" style="width:10%">تعداد</th>
                        <th scope="col" style="width:10%">گروه </th>
                        <th scope="col" style="width:10%">وضعیت</th>
                        <th scope="col" style="width:20%">نویسنده و تاریخ نگارش</th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@couter</th>
                                <td>
                                    <strong><a class="text-decoration-none" asp-area="Admin" asp-controller="Home" asp-action="Index" asp-route-id="@item.Id">@item.PrimaryTitle</a></strong><br />
                                    <span class="text-muted">شناسه :@item.Id</span>
                                </td>
                                <td>@item.Count</td>
                                <td>@item.group?.GroupTitle</td>
                                @if (item.state == StufShop.Models.Stuf.State.Enabled)
                                {
                                    <td>فعال</td>

                                }
                                else
                                {
                                    <td>غیر فعال</td>

                                }
                                <td style="width: 20%"><span>@item.Creator</span><br /><strong class="text-muted">تاریخ: @item.CreateDate</strong></td>


                                <td class="align-middle">
                                    <div class="dropdown">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                            <li><a class="dropdown-item" asp-area="Admin" asp-action="Edit" asp-route-Id="@item.Id">ویرایش</a></li>
                                            <li><a class="dropdown-item text-danger" asp-area="Admin" asp-action="Delete" asp-route-Id="@item.Id">حذف</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            { couter++; }
                        }
                    }

                </tbody>
            </table>
 

        </div>
    </div>


    <br />
    <br />

}

StufShop/Areas/Admin/Views/Stuf/save.cshtml
@page
 
@{
}
<h3>Save</h3>